# Generated by Django 4.2.5 on 2023-10-03 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olymphistory_bot', '0007_alter_epoch_image_alter_question_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытка',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250, verbose_name='Ответ')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymphistory_bot.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymphistory_bot.question')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='questions',
            field=models.ManyToManyField(through='olymphistory_bot.UserAnswer', to='olymphistory_bot.question', verbose_name='Вопросы'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymphistory_bot.telegramuser', verbose_name='Пользователь'),
        ),
    ]
