# Generated by Django 4.2.5 on 2023-10-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymphistory_bot', '0008_attempt_useranswer_attempt_questions_attempt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='right',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
