# Generated by Django 4.2.5 on 2023-10-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olymphistory_bot', '0009_useranswer_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olymphistory_bot.note', verbose_name='Заметка'),
        ),
    ]
