# Generated by Django 4.1 on 2023-10-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymphistory_bot', '0010_question_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notes', verbose_name='Картинка'),
        ),
    ]
