# Generated by Django 4.1 on 2023-10-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymphistory_bot', '0011_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoch',
            name='emoji',
            field=models.CharField(blank=True, max_length=1, verbose_name='Эмодзи'),
        ),
    ]
