# Generated by Django 4.1 on 2023-10-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olymphistory_bot', '0012_epoch_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epoch',
            name='emoji',
        ),
    ]
