# Generated by Django 4.1 on 2024-01-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olymphistory_bot', '0014_alter_question_epoch_alter_question_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(blank=True, max_length=25, null=True, verbose_name='Начало')),
                ('end_year', models.CharField(blank=True, max_length=25, null=True, verbose_name='Конец')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='epochs', verbose_name='Картинка')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Правитель',
                'verbose_name_plural': 'Правители',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olymphistory_bot.leader', verbose_name='Эпоха'),
        ),
    ]
