# Generated by Django 4.1 on 2024-01-19 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olymphistory_bot', '0015_leader_question_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olymphistory_bot.leader', verbose_name='Правитель'),
        ),
    ]
